export const investmentPlans = [
  {
    package: "Platinum Plan",
    color1: "CF9B03",
    packageBenefit: [
      "99.5% AI accuracy",
      "24/7 Priority support",
      "Exclusive market insights",
      "Zero trading fees",
      "Dedicated account manager",
      "VIP event invitations",
      "Customized portfolio",
      "Early access to opportunities",
      "98% execellent mining power",
    ],
    image: "/assets/premiumm.png",
    minprice: 1000000,
    maxprice: 10000000,
    duration: "2 Weeks",
  },
  {
    package: "Gold Plan",
    color1: "6B4BC9",
    packageBenefit: [
      "99% AI accuracy",
      "Extended support hours",
      "Premium market insights",
      "Reduced trading fees",
      "Personalized strategies",
      "Exclusive webinars",
      "Flexible withdrawal options",
      "60% execellent mining power",
    ],
    image: "/assets/gold.png",
    minprice: 100000,
    maxprice: 999999,
    duration: "2 Weeks",
  },
  {
    package: "Silver Plan",
    color1: "C0C0C0",
    packageBenefit: [
      "98% AI accuracy",
      "Advanced market insights",
      "Loyalty discounts",
      "Educational resources",
      "Weekly market analysis",
      "Investment community access",
      "Enhanced security",
      "45% execellent mining power",
    ],
    image: "/assets/silverr.png",
    minprice: 10000,
    maxprice: 99999,
    duration: "2 Weeks",
  },
  {
    package: "Mini Plan",
    color1: "CD7F32",
    packageBenefit: [
      "97% AI accuracy",
      "Live chat support",
      "Basic market insights",
      "Competitive fees",
      "Monthly market analysis",
      "Community forums",
      "Mobile app support",
      "20% execellent mining power",
    ],
    image: "/assets/bronze.png",
    minprice: 500,
    maxprice: 9999,
    duration: "2 Weeks",
  },
];
