export const investmentPlans = [
  {
    package: "Signal Subscription",
    color1: "CF9B03",
    packageBenefit: [
      "99.5% AI accuracy",
      "24/7 Priority support",
      "Exclusive market insights",
      "Zero trading fees",
      "Dedicated account manager",
      "VIP event invitations",
      "Customized portfolio",
      "Early access to opportunities",
    ],
    image: "/assets/premiumm.png",
    price: 2050,
    duration: "6mo",
  },
  {
    package: "Signal Subscription",
    color1: "6B4BC9",
    packageBenefit: [
      "99% AI accuracy",
      "Extended support hours",
      "Premium market insights",
      "Reduced trading fees",
      "Personalized strategies",
      "Exclusive webinars",
      "Flexible withdrawal options",
    ],
    image: "/assets/gold.png",
    price: 1550,
    duration: "1mo",
  },
  {
    package: "Signal Subscription",
    color1: "C0C0C0",
    packageBenefit: [
      "98% AI accuracy",
      "Advanced market insights",
      "Loyalty discounts",
      "Educational resources",
      "Weekly market analysis",
      "Investment community access",
      "Enhanced security",
    ],
    image: "/assets/silverr.png",
    price: 1050,
    duration: "1 Week",
  },
  {
    package: "Signal Subscription",
    color1: "CD7F32",
    packageBenefit: [
      "97% AI accuracy",
      "Live chat support",
      "Basic market insights",
      "Competitive fees",
      "Monthly market analysis",
      "Community forums",
      "Mobile app support",
    ],
    image: "/assets/bronze.png",
    price: 550,
    duration: "24 Hrs",
  },
];
